### ISSUE TITLE
Internal simulator works not as it expected.

### ISSUE THREAD

**Issue by michael3m** [maziac/DeZog#124]
**Describe the bug**
Program writes data into unexpected area.

**To Reproduce**
Just run attached project file in internal simulator.

**Expected behavior**
https://youtu.be/Nb9JCW7X6eg

**Screenshots**
https://youtu.be/3N0D_kScFbc

**Version etc. (please complete the following information):**
 - DeZog SW Version: 3.2.2
 - OS: Windows 11 Professional x64
 - Remote: zsim or zrcp (ZEsarUX): none. 

**Additional context**
VSCode project file:
https://mega.nz/file/KEtAGZwS#oy_OEoI536vtmbVz8K37JQMa1zNBc4F3kioAD23T9Rw

**Comment by maziac** [comment]
From what I can see there is a mismatch of the assembled memory model in arrow.asm (ZXSPECTRUM48) and the one used for the simulator (ZX128K).
If you change in  launch.json to "ZX48K" it  starts to work:
![Bildschirmfoto 2024-02-12 um 15 53 05](https://github.com/maziac/DeZog/assets/3081973/d2350719-ce43-4b6a-afd9-3af38c7fdb57)

I would guess that it is because the wrong ROM is used or maybe a wrong bank.

**Comment by michael3m** [comment]
Sigh, I should've paid more attention to content of .vscode files, when copy it from one project to another one.
Sorry.

**Comment by maziac** [comment]
No problem.
