### ISSUE TITLE
Unit Tests: "Code for tests is not present" error instead of tests being run (v2.3.2)

### ISSUE THREAD

**Issue by evolutional** [maziac/DeZog#71]
**Describe the bug**
When using the Unit Test feature, I get the error "Code for tests is not present" when attempting to run a test.

**To Reproduce**
See example in [this repository](https://github.com/evolutional/dzut) which mirrors my typical project set up and how I am trying to use the testing system.

It has two NEX files, one for the "game" and one for the "tests".

- I build the tests using the "Build tests" task
- I then refresh the test explorer
- Run all tests in suite

**Expected behavior**
Expected the unit tests to run correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/2247662/134630256-5a1e152a-a7f8-46fd-a3d9-ce032fd06b94.png)

![image](https://user-images.githubusercontent.com/2247662/134630472-3ed6c804-f5e2-4394-a0b2-7b44084a1485.png)

**Version etc. (please complete the following information):**
 - DeZog SW Version: v2.3.2
 - OS: Windows 10 (latest build)
 - Remote: zsim for the tests, cspect for the main game test

**Additional context**
Project is in the repo https://github.com/evolutional/dzut

**Comment by maziac** [comment]
It's running now.
Basic problem was that the tests origin was at 0x0000. I moved it to 0xC000.

Please note: I haven't tested with DeZog v2.3.2 but with the current beta 2.4.0-6.
Please upgrade:
https://github.com/maziac/DeZog/releases/tag/v2.4.0-x

I attached your project with the changes here:
[dzut.zip](https://github.com/maziac/DeZog/files/7227158/dzut.zip)

Other changes I did:
- launch.json: 
  - presentation/hidden: with that the unit tests don't appear in vscode's debug launcher
  - "zsim" configuration for ZXNext, i.e. support for Z80N instructions. Just in case you want to use that in the future.
- task.json: both tasks were "default"
- test.z80: ORG 0xC000. Otherwise the tests are in the ROM area.
- unit_tests.inc: updated to newer version (for DeZog 2.4).

Furthermore:
You can deinstall the "Z80 Unit Tests" extension. If you leave it in you might experience to find 2 kind of unit tests, could be irritating.

Please let me know if it works.

**Comment by evolutional** [comment]
Ah, perfect! That was it exactly - verified on v2.3.2

Sorry for the dumb user report!
